import type {
  ActivityLog,
  Balance,
  CapTableEntry,
  Certificate,
  ComplianceProfile,
  Document,
  Hold,
  Investor,
  Issuer,
  LedgerEntry,
  Lockup,
  Security,
  Transfer,
  TransferRequest,
} from '../_types';

// ─── Issuers ──────────────────────────────────────────────────────────────────
export const issuers: Issuer[] = [
  {
    id: 'ISS-001',
    name: 'Apex Ventures Inc.',
    ein: '82-1234567',
    state: 'Delaware',
    status: 'active',
    securitiesCount: 3,
    investorsCount: 142,
    createdAt: '2022-03-15',
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.chen@apexventures.com',
    address: '1 Market St, San Francisco, CA 94105',
    totalSharesIssued: 5_000_000,
  },
  {
    id: 'ISS-002',
    name: 'Meridian Biotech LLC',
    ein: '45-9876543',
    state: 'Nevada',
    status: 'active',
    securitiesCount: 2,
    investorsCount: 78,
    createdAt: '2021-07-22',
    contactName: 'Dr. James Park',
    contactEmail: 'jpark@meridianbio.com',
    address: '200 Life Sciences Blvd, Boston, MA 02115',
    totalSharesIssued: 10_000_000,
  },
  {
    id: 'ISS-003',
    name: 'Solaris Energy Corp',
    ein: '91-2345678',
    state: 'Wyoming',
    status: 'active',
    securitiesCount: 1,
    investorsCount: 35,
    createdAt: '2023-01-10',
    contactName: 'Maria Vasquez',
    contactEmail: 'mvasquez@solariscorp.com',
    address: '750 Energy Way, Houston, TX 77002',
    totalSharesIssued: 2_000_000,
  },
  {
    id: 'ISS-004',
    name: 'NovaTech Systems',
    ein: '37-4567890',
    state: 'California',
    status: 'pending',
    securitiesCount: 0,
    investorsCount: 0,
    createdAt: '2024-06-01',
    contactName: 'Alex Rivera',
    contactEmail: 'arivera@novatech.io',
    address: '3000 Innovation Dr, Austin, TX 78701',
    totalSharesIssued: 0,
  },
  {
    id: 'ISS-005',
    name: 'Harbor Capital Group',
    ein: '56-7890123',
    state: 'Florida',
    status: 'inactive',
    securitiesCount: 1,
    investorsCount: 12,
    createdAt: '2020-11-30',
    contactName: "Patricia O'Brien",
    contactEmail: 'pobrien@harborcapital.com',
    address: '400 Brickell Ave, Miami, FL 33131',
    totalSharesIssued: 500_000,
  },
];

// ─── Securities ────────────────────────────────────────────────────────────────
export const securities: Security[] = [
  {
    id: 'SEC-001',
    issuerId: 'ISS-001',
    issuerName: 'Apex Ventures Inc.',
    name: 'Apex Common Stock',
    ticker: 'APEX',
    type: 'common-stock',
    totalAuthorized: 10_000_000,
    totalIssued: 5_000_000,
    totalOutstanding: 4_850_000,
    parValue: 0.001,
    status: 'active',
    cusip: 'APEX0001C',
    createdAt: '2022-03-15',
  },
  {
    id: 'SEC-002',
    issuerId: 'ISS-001',
    issuerName: 'Apex Ventures Inc.',
    name: 'Apex Series A Preferred',
    ticker: 'APEX-A',
    type: 'preferred-stock',
    totalAuthorized: 3_000_000,
    totalIssued: 2_000_000,
    totalOutstanding: 2_000_000,
    parValue: 0.001,
    status: 'active',
    cusip: 'APEX0002P',
    createdAt: '2022-09-01',
  },
  {
    id: 'SEC-003',
    issuerId: 'ISS-001',
    issuerName: 'Apex Ventures Inc.',
    name: 'Apex Series A Warrants',
    ticker: 'APEX-W',
    type: 'warrant',
    totalAuthorized: 500_000,
    totalIssued: 300_000,
    totalOutstanding: 300_000,
    parValue: 0,
    status: 'active',
    cusip: 'APEX0003W',
    createdAt: '2022-09-01',
  },
  {
    id: 'SEC-004',
    issuerId: 'ISS-002',
    issuerName: 'Meridian Biotech LLC',
    name: 'Meridian Common Shares',
    ticker: 'MRDNC',
    type: 'common-stock',
    totalAuthorized: 20_000_000,
    totalIssued: 10_000_000,
    totalOutstanding: 9_500_000,
    parValue: 0.0001,
    status: 'active',
    cusip: 'MRDN0001C',
    createdAt: '2021-07-22',
  },
  {
    id: 'SEC-005',
    issuerId: 'ISS-002',
    issuerName: 'Meridian Biotech LLC',
    name: 'Meridian Convertible Note',
    ticker: 'MRDNB',
    type: 'bond',
    totalAuthorized: 5_000_000,
    totalIssued: 3_000_000,
    totalOutstanding: 3_000_000,
    parValue: 1,
    status: 'active',
    cusip: 'MRDN0002B',
    createdAt: '2023-02-14',
  },
  {
    id: 'SEC-006',
    issuerId: 'ISS-003',
    issuerName: 'Solaris Energy Corp',
    name: 'Solaris Common Stock',
    ticker: 'SLRS',
    type: 'common-stock',
    totalAuthorized: 5_000_000,
    totalIssued: 2_000_000,
    totalOutstanding: 2_000_000,
    parValue: 0.01,
    status: 'active',
    cusip: 'SLRS0001C',
    createdAt: '2023-01-10',
  },
];

// ─── Investors ────────────────────────────────────────────────────────────────
export const investors: Investor[] = [
  {
    id: 'INV-001',
    name: 'Robert Chambers',
    email: 'rchambers@email.com',
    type: 'individual',
    status: 'active',
    accredited: true,
    taxId: '***-**-4521',
    address: '123 Oak Lane, Greenwich, CT 06830',
    phone: '+1 (203) 555-0101',
    kyc: 'approved',
    createdAt: '2022-04-10',
    totalShares: 150_000,
    totalValue: 750_000,
  },
  {
    id: 'INV-002',
    name: 'Lighthouse Capital Partners',
    email: 'invest@lighthousecap.com',
    type: 'institutional',
    status: 'active',
    accredited: true,
    crdNumber: 'CRD-298473',
    taxId: '43-7654321',
    address: '500 Park Ave, New York, NY 10022',
    phone: '+1 (212) 555-0202',
    kyc: 'approved',
    createdAt: '2022-03-20',
    totalShares: 800_000,
    totalValue: 4_000_000,
  },
  {
    id: 'INV-003',
    name: 'Jennifer Patel',
    email: 'jpatel@techfirm.io',
    type: 'individual',
    status: 'active',
    accredited: true,
    taxId: '***-**-8832',
    address: '88 Market St, San Francisco, CA 94102',
    phone: '+1 (415) 555-0303',
    kyc: 'approved',
    createdAt: '2022-05-15',
    totalShares: 50_000,
    totalValue: 250_000,
  },
  {
    id: 'INV-004',
    name: 'Sunrise Family Trust',
    email: 'trustee@sunrisetrust.com',
    type: 'trust',
    status: 'active',
    accredited: true,
    taxId: '87-1234567',
    address: '720 Palm Dr, Beverly Hills, CA 90210',
    phone: '+1 (310) 555-0404',
    kyc: 'approved',
    createdAt: '2021-09-01',
    totalShares: 200_000,
    totalValue: 1_000_000,
  },
  {
    id: 'INV-005',
    name: 'Marcus Webb',
    email: 'mwebb@outlook.com',
    type: 'individual',
    status: 'pending',
    accredited: false,
    taxId: '***-**-2219',
    address: '45 River Rd, Portland, OR 97201',
    phone: '+1 (503) 555-0505',
    kyc: 'pending',
    createdAt: '2024-08-22',
    totalShares: 0,
    totalValue: 0,
  },
  {
    id: 'INV-006',
    name: 'Orion Asset Management',
    email: 'deals@orionam.com',
    type: 'institutional',
    status: 'active',
    accredited: true,
    crdNumber: 'CRD-445521',
    taxId: '22-8899001',
    address: '1 Financial Center, Boston, MA 02111',
    phone: '+1 (617) 555-0606',
    kyc: 'approved',
    createdAt: '2021-11-05',
    totalShares: 500_000,
    totalValue: 2_500_000,
  },
  {
    id: 'INV-007',
    name: 'Diana Foster',
    email: 'dfoster@law.com',
    type: 'individual',
    status: 'suspended',
    accredited: true,
    taxId: '***-**-7731',
    address: '290 Broadway, New York, NY 10007',
    phone: '+1 (212) 555-0707',
    kyc: 'rejected',
    createdAt: '2023-03-12',
    totalShares: 25_000,
    totalValue: 125_000,
  },
];

// ─── Transfers ────────────────────────────────────────────────────────────────
export const transfers: Transfer[] = [
  {
    id: 'TRF-001',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    fromInvestorId: 'INV-001',
    fromInvestorName: 'Robert Chambers',
    toInvestorId: 'INV-003',
    toInvestorName: 'Jennifer Patel',
    shares: 10_000,
    pricePerShare: 5.0,
    totalAmount: 50_000,
    status: 'pending',
    type: 'secondary',
    submittedAt: '2025-01-15',
    notes: 'Secondary market sale between accredited investors',
  },
  {
    id: 'TRF-002',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    fromInvestorId: 'INV-002',
    fromInvestorName: 'Lighthouse Capital Partners',
    toInvestorId: 'INV-006',
    toInvestorName: 'Orion Asset Management',
    shares: 50_000,
    pricePerShare: 8.75,
    totalAmount: 437_500,
    status: 'approved',
    type: 'secondary',
    submittedAt: '2025-01-10',
    approvedBy: 'OA Admin',
  },
  {
    id: 'TRF-003',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    fromInvestorId: 'INV-004',
    fromInvestorName: 'Sunrise Family Trust',
    toInvestorId: 'INV-001',
    toInvestorName: 'Robert Chambers',
    shares: 5_000,
    pricePerShare: 0,
    totalAmount: 0,
    status: 'completed',
    type: 'gift',
    submittedAt: '2024-12-20',
    completedAt: '2024-12-28',
    approvedBy: 'Sarah Mitchell',
  },
  {
    id: 'TRF-004',
    securityId: 'SEC-006',
    securityName: 'Solaris Common Stock',
    fromInvestorId: 'INV-006',
    fromInvestorName: 'Orion Asset Management',
    toInvestorId: 'INV-002',
    toInvestorName: 'Lighthouse Capital Partners',
    shares: 20_000,
    pricePerShare: 12.5,
    totalAmount: 250_000,
    status: 'rejected',
    type: 'secondary',
    submittedAt: '2025-01-05',
    notes: 'Rejected: missing KYC documentation for receiving party',
  },
  {
    id: 'TRF-005',
    securityId: 'SEC-002',
    securityName: 'Apex Series A Preferred',
    fromInvestorId: 'INV-002',
    fromInvestorName: 'Lighthouse Capital Partners',
    toInvestorId: 'INV-004',
    toInvestorName: 'Sunrise Family Trust',
    shares: 25_000,
    pricePerShare: 10.0,
    totalAmount: 250_000,
    status: 'pending',
    type: 'secondary',
    submittedAt: '2025-01-18',
  },
];

// ─── Transfer Requests ────────────────────────────────────────────────────────
export const transferRequests: TransferRequest[] = [
  {
    id: 'TRQ-001',
    investorId: 'INV-001',
    investorName: 'Robert Chambers',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    toName: 'Jennifer Patel',
    toEmail: 'jpatel@techfirm.io',
    shares: 10_000,
    reason: 'Private sale per investment agreement',
    status: 'under-review',
    submittedAt: '2025-01-15',
    documents: ['Form-144.pdf', 'Transfer-Agreement.pdf'],
  },
  {
    id: 'TRQ-002',
    investorId: 'INV-004',
    investorName: 'Sunrise Family Trust',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    toName: 'Robert Chambers',
    toEmail: 'rchambers@email.com',
    shares: 5_000,
    reason: 'Gift to family member',
    status: 'approved',
    submittedAt: '2024-12-18',
    reviewedAt: '2024-12-22',
    reviewedBy: 'Sarah Mitchell',
    documents: ['Gift-Letter.pdf'],
  },
  {
    id: 'TRQ-003',
    investorId: 'INV-003',
    investorName: 'Jennifer Patel',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    toName: 'Marcus Webb',
    toEmail: 'mwebb@outlook.com',
    shares: 2_000,
    reason: 'Secondary sale',
    status: 'pending',
    submittedAt: '2025-01-20',
    documents: ['Purchase-Agreement.pdf'],
  },
];

// ─── Ledger Entries ───────────────────────────────────────────────────────────
export const ledgerEntries: LedgerEntry[] = [
  {
    id: 'LED-001',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    investorId: 'INV-001',
    investorName: 'Robert Chambers',
    type: 'issuance',
    shares: 150_000,
    balanceBefore: 0,
    balanceAfter: 150_000,
    timestamp: '2022-04-10T14:23:00Z',
    reference: 'INITIAL-ISSUANCE',
    approvedBy: 'Sarah Mitchell',
  },
  {
    id: 'LED-002',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    type: 'issuance',
    shares: 500_000,
    balanceBefore: 0,
    balanceAfter: 500_000,
    timestamp: '2022-03-20T09:00:00Z',
    reference: 'SERIES-A-ROUND',
    approvedBy: 'Sarah Mitchell',
  },
  {
    id: 'LED-003',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    investorId: 'INV-004',
    investorName: 'Sunrise Family Trust',
    type: 'transfer',
    shares: -5_000,
    balanceBefore: 200_000,
    balanceAfter: 195_000,
    timestamp: '2024-12-28T11:30:00Z',
    reference: 'TRF-003',
    approvedBy: 'Sarah Mitchell',
  },
  {
    id: 'LED-004',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    investorId: 'INV-001',
    investorName: 'Robert Chambers',
    type: 'transfer',
    shares: 5_000,
    balanceBefore: 145_000,
    balanceAfter: 150_000,
    timestamp: '2024-12-28T11:30:00Z',
    reference: 'TRF-003',
    approvedBy: 'Sarah Mitchell',
  },
  {
    id: 'LED-005',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    type: 'issuance',
    shares: 800_000,
    balanceBefore: 0,
    balanceAfter: 800_000,
    timestamp: '2021-07-22T10:00:00Z',
    reference: 'INITIAL-ISSUANCE',
    approvedBy: 'James Park',
  },
  {
    id: 'LED-006',
    securityId: 'SEC-002',
    securityName: 'Apex Series A Preferred',
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    type: 'issuance',
    shares: 250_000,
    balanceBefore: 0,
    balanceAfter: 250_000,
    timestamp: '2022-09-01T09:00:00Z',
    reference: 'SERIES-A-PREF',
    approvedBy: 'Sarah Mitchell',
  },
];

// ─── Holds ────────────────────────────────────────────────────────────────────
export const holds: Hold[] = [
  {
    id: 'HLD-001',
    investorId: 'INV-007',
    investorName: 'Diana Foster',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    type: 'regulatory',
    shares: 25_000,
    reason: 'SEC investigation — restricted trading pending review',
    startDate: '2024-11-01',
    status: 'active',
    issuedBy: 'OA Compliance Team',
  },
  {
    id: 'HLD-002',
    investorId: 'INV-001',
    investorName: 'Robert Chambers',
    securityId: 'SEC-002',
    securityName: 'Apex Series A Preferred',
    type: 'legal',
    shares: 10_000,
    reason: 'Pending court order — estate dispute',
    startDate: '2024-10-15',
    endDate: '2025-03-15',
    status: 'active',
    issuedBy: 'Legal Department',
  },
  {
    id: 'HLD-003',
    investorId: 'INV-003',
    investorName: 'Jennifer Patel',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    type: 'voluntary',
    shares: 5_000,
    reason: 'Investor requested voluntary hold during divorce proceedings',
    startDate: '2024-09-01',
    endDate: '2025-09-01',
    status: 'active',
    issuedBy: 'Jennifer Patel (self)',
  },
];

// ─── Lockups ──────────────────────────────────────────────────────────────────
export const lockups: Lockup[] = [
  {
    id: 'LKP-001',
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 300_000,
    lockupDays: 365,
    startDate: '2022-03-20',
    endDate: '2023-03-20',
    status: 'released',
    reason: 'Series A investor lockup agreement',
  },
  {
    id: 'LKP-002',
    investorId: 'INV-004',
    investorName: 'Sunrise Family Trust',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    shares: 100_000,
    lockupDays: 180,
    startDate: '2024-07-01',
    endDate: '2024-12-28',
    status: 'released',
    reason: 'IPO preparatory lockup',
  },
  {
    id: 'LKP-003',
    investorId: 'INV-006',
    investorName: 'Orion Asset Management',
    securityId: 'SEC-006',
    securityName: 'Solaris Common Stock',
    shares: 200_000,
    lockupDays: 365,
    startDate: '2024-01-10',
    endDate: '2025-01-10',
    status: 'active',
    reason: 'Strategic investor lockup — Solaris seed round',
  },
];

// ─── Compliance Profiles ──────────────────────────────────────────────────────
export const complianceProfiles: ComplianceProfile[] = [
  {
    issuerId: 'ISS-001',
    issuerName: 'Apex Ventures Inc.',
    exemption: 'Reg D 506(b)',
    maxInvestors: 2000,
    currentInvestors: 142,
    formDFiled: true,
    blueSkyStates: ['CA', 'NY', 'TX', 'FL', 'WA'],
    restrictions: ['No general solicitation', 'Accredited investors only for 506(b)'],
    lastReviewed: '2024-12-01',
    nextReview: '2025-06-01',
    status: 'compliant',
  },
  {
    issuerId: 'ISS-002',
    issuerName: 'Meridian Biotech LLC',
    exemption: 'Reg D 506(c)',
    maxInvestors: 2000,
    currentInvestors: 78,
    formDFiled: true,
    blueSkyStates: ['MA', 'CT', 'NJ', 'NY'],
    restrictions: ['General solicitation allowed', 'Accredited investors only'],
    lastReviewed: '2024-11-15',
    nextReview: '2025-05-15',
    status: 'compliant',
  },
  {
    issuerId: 'ISS-003',
    issuerName: 'Solaris Energy Corp',
    exemption: 'Reg A+',
    maxInvestors: 2000,
    currentInvestors: 35,
    formDFiled: false,
    blueSkyStates: ['TX', 'CO', 'OK', 'NM'],
    restrictions: ['Offering circular required', 'Annual reporting obligation'],
    lastReviewed: '2025-01-05',
    nextReview: '2025-07-05',
    status: 'review-needed',
  },
];

// ─── Certificates ─────────────────────────────────────────────────────────────
export const certificates: Certificate[] = [
  {
    id: 'CERT-001',
    investorId: 'INV-001',
    securityId: 'SEC-001',
    shares: 150_000,
    issueDate: '2022-04-10',
    status: 'active',
    certificateNumber: 'APEX-C-0001',
  },
  {
    id: 'CERT-002',
    investorId: 'INV-002',
    securityId: 'SEC-001',
    shares: 500_000,
    issueDate: '2022-03-20',
    status: 'active',
    certificateNumber: 'APEX-C-0002',
  },
  {
    id: 'CERT-003',
    investorId: 'INV-004',
    securityId: 'SEC-001',
    shares: 200_000,
    issueDate: '2021-09-01',
    status: 'active',
    certificateNumber: 'APEX-C-0003',
  },
];

// ─── Balances ─────────────────────────────────────────────────────────────────
export const balances: Balance[] = [
  {
    investorId: 'INV-001',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 150_000,
    vestedShares: 150_000,
    heldShares: 0,
    availableShares: 150_000,
    lastUpdated: '2024-12-28',
    currentValue: 750_000,
  },
  {
    investorId: 'INV-001',
    securityId: 'SEC-002',
    securityName: 'Apex Series A Preferred',
    shares: 10_000,
    vestedShares: 10_000,
    heldShares: 10_000,
    availableShares: 0,
    lastUpdated: '2024-10-15',
    currentValue: 100_000,
  },
  {
    investorId: 'INV-002',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 500_000,
    vestedShares: 500_000,
    heldShares: 0,
    availableShares: 450_000,
    lastUpdated: '2025-01-10',
    currentValue: 2_500_000,
  },
  {
    investorId: 'INV-002',
    securityId: 'SEC-004',
    securityName: 'Meridian Common Shares',
    shares: 800_000,
    vestedShares: 800_000,
    heldShares: 0,
    availableShares: 750_000,
    lastUpdated: '2025-01-10',
    currentValue: 7_000_000,
  },
];

// ─── Cap Table ────────────────────────────────────────────────────────────────
export const capTableEntries: CapTableEntry[] = [
  {
    investorId: 'INV-001',
    investorName: 'Robert Chambers',
    investorType: 'Individual',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 150_000,
    percentage: 3.09,
    issueDate: '2022-04-10',
    certificateIds: ['CERT-001'],
    value: 750_000,
  },
  {
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    investorType: 'Institutional',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 500_000,
    percentage: 10.31,
    issueDate: '2022-03-20',
    certificateIds: ['CERT-002'],
    value: 2_500_000,
  },
  {
    investorId: 'INV-004',
    investorName: 'Sunrise Family Trust',
    investorType: 'Trust',
    securityId: 'SEC-001',
    securityName: 'Apex Common Stock',
    shares: 195_000,
    percentage: 4.02,
    issueDate: '2021-09-01',
    certificateIds: ['CERT-003'],
    value: 975_000,
  },
  {
    investorId: 'INV-002',
    investorName: 'Lighthouse Capital Partners',
    investorType: 'Institutional',
    securityId: 'SEC-002',
    securityName: 'Apex Series A Preferred',
    shares: 250_000,
    percentage: 12.5,
    issueDate: '2022-09-01',
    certificateIds: [],
    value: 2_500_000,
  },
  {
    investorId: 'INV-006',
    investorName: 'Orion Asset Management',
    investorType: 'Institutional',
    securityId: 'SEC-006',
    securityName: 'Solaris Common Stock',
    shares: 500_000,
    percentage: 25.0,
    issueDate: '2023-01-10',
    certificateIds: [],
    value: 6_250_000,
  },
];

// ─── Documents ─────────────────────────────────────────────────────────────────
export const documents: Document[] = [
  {
    id: 'DOC-001',
    name: 'Stock Certificate APEX-C-0001',
    type: 'PDF',
    size: '245 KB',
    uploadedAt: '2022-04-10',
    status: 'active',
    category: 'agreement',
  },
  {
    id: 'DOC-002',
    name: 'KYC Verification — Robert Chambers',
    type: 'PDF',
    size: '1.2 MB',
    uploadedAt: '2022-04-08',
    status: 'active',
    category: 'kyc',
  },
  {
    id: 'DOC-003',
    name: 'Investment Agreement (Series A)',
    type: 'PDF',
    size: '890 KB',
    uploadedAt: '2022-03-15',
    status: 'active',
    category: 'agreement',
  },
  {
    id: 'DOC-004',
    name: 'Annual Statement 2024',
    type: 'PDF',
    size: '320 KB',
    uploadedAt: '2025-01-05',
    status: 'active',
    category: 'statement',
  },
  {
    id: 'DOC-005',
    name: 'Form 1099-B (2024)',
    type: 'PDF',
    size: '180 KB',
    uploadedAt: '2025-01-15',
    status: 'active',
    category: 'tax',
  },
  {
    id: 'DOC-006',
    name: 'Transfer Agreement TRF-003',
    type: 'PDF',
    size: '445 KB',
    uploadedAt: '2024-12-20',
    status: 'active',
    category: 'agreement',
  },
];

// ─── Activity Logs ────────────────────────────────────────────────────────────
export const activityLogs: ActivityLog[] = [
  {
    id: 'ACT-001',
    userId: 'U-001',
    userName: 'Sarah Mitchell',
    userRole: 'OA Admin',
    action: 'Approved Transfer',
    entityType: 'Transfer',
    entityId: 'TRF-003',
    timestamp: '2024-12-28T11:30:00Z',
    ipAddress: '192.168.1.1',
    details: 'Approved gift transfer of 5,000 shares from Sunrise Family Trust to Robert Chambers',
  },
  {
    id: 'ACT-002',
    userId: 'U-002',
    userName: 'James Park',
    userRole: 'Issuer Admin',
    action: 'Issued Security',
    entityType: 'Security',
    entityId: 'SEC-005',
    timestamp: '2023-02-14T09:15:00Z',
    ipAddress: '10.0.0.5',
    details: 'Created Meridian Convertible Note with 3,000,000 units',
  },
  {
    id: 'ACT-003',
    userId: 'U-001',
    userName: 'Sarah Mitchell',
    userRole: 'OA Admin',
    action: 'Placed Hold',
    entityType: 'Hold',
    entityId: 'HLD-001',
    timestamp: '2024-11-01T14:00:00Z',
    ipAddress: '192.168.1.1',
    details: 'Regulatory hold placed on Diana Foster — 25,000 shares Apex Common Stock',
  },
  {
    id: 'ACT-004',
    userId: 'U-003',
    userName: 'Tom Bradley',
    userRole: 'Operator',
    action: 'Reviewed Transfer Request',
    entityType: 'TransferRequest',
    entityId: 'TRQ-001',
    timestamp: '2025-01-16T10:22:00Z',
    ipAddress: '10.0.0.8',
    details: 'Marked TRQ-001 as under-review — awaiting Form 144 verification',
  },
  {
    id: 'ACT-005',
    userId: 'U-001',
    userName: 'Sarah Mitchell',
    userRole: 'OA Admin',
    action: 'Created Investor',
    entityType: 'Investor',
    entityId: 'INV-005',
    timestamp: '2024-08-22T08:45:00Z',
    ipAddress: '192.168.1.1',
    details: 'New investor profile created for Marcus Webb — KYC pending',
  },
  {
    id: 'ACT-006',
    userId: 'U-004',
    userName: 'Priya Nair',
    userRole: 'Auditor',
    action: 'Exported Ledger',
    entityType: 'Ledger',
    entityId: 'SEC-001',
    timestamp: '2025-01-19T15:00:00Z',
    ipAddress: '10.0.1.2',
    details: 'Exported full ledger for Apex Common Stock — 6 entries',
  },
];

// ─── Dashboard Chart Data ─────────────────────────────────────────────────────
export const transfersChartData = [
  { month: 'Aug', pending: 3, approved: 8, completed: 12 },
  { month: 'Sep', pending: 5, approved: 10, completed: 15 },
  { month: 'Oct', pending: 4, approved: 7, completed: 11 },
  { month: 'Nov', pending: 6, approved: 12, completed: 18 },
  { month: 'Dec', pending: 8, approved: 9, completed: 14 },
  { month: 'Jan', pending: 5, approved: 11, completed: 16 },
];

export const capTableChartData = [
  { name: 'Lighthouse Capital', value: 35.2, fill: 'var(--chart-1)' },
  { name: 'Orion Asset Mgmt', value: 22.1, fill: 'var(--chart-2)' },
  { name: 'Sunrise Family Trust', value: 15.8, fill: 'var(--chart-3)' },
  { name: 'Robert Chambers', value: 8.4, fill: 'var(--chart-4)' },
  { name: 'Others', value: 18.5, fill: 'var(--chart-5)' },
];
